/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  DelegatooorFactory,
  DelegatooorFactoryInterface,
} from "../DelegatooorFactory";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    name: "DelegatooorDeploy",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "_bytecode",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "_salt",
        type: "uint256",
      },
    ],
    name: "deploy",
    outputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061027f806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80639c4ae2d014610030575b600080fd5b61004361003e3660046101c5565b610059565b604051610050919061023b565b60405180910390f35b6000818351602085016000f59050803b61007257600080fd5b7f22cf15067611f22a5ad360d3f92a7a10471eec11686cbe36fc57a8efd5dcab63816040516100a1919061023b565b60405180910390a192915050565b601f01601f191690565b634e487b7160e01b600052604160045260246000fd5b6100d8826100af565b81018181106001600160401b03821117156100f5576100f56100b9565b6040525050565b600061010760405190565b905061011382826100cf565b919050565b60006001600160401b03821115610131576101316100b9565b61013a826100af565b60200192915050565b82818337506000910152565b600061016261015d84610118565b6100fc565b90508281526020810184848401111561017d5761017d600080fd5b610188848285610143565b509392505050565b600082601f8301126101a4576101a4600080fd5b81356101b484826020860161014f565b949350505050565b80355b92915050565b600080604083850312156101db576101db600080fd5b82356001600160401b038111156101f4576101f4600080fd5b61020085828601610190565b9250506020610211858286016101bc565b9150509250929050565b60006001600160a01b0382166101bf565b6102358161021b565b82525050565b602081016101bf828461022c56fea26469706673582212202885ca3b031d0628041165dd503a8c4d10ef2da2e21a5686a6b50bee0e3c867e64736f6c63430008120033";

type DelegatooorFactoryConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DelegatooorFactoryConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DelegatooorFactory__factory extends ContractFactory {
  constructor(...args: DelegatooorFactoryConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
    this.contractName = "DelegatooorFactory";
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<DelegatooorFactory> {
    return super.deploy(overrides || {}) as Promise<DelegatooorFactory>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): DelegatooorFactory {
    return super.attach(address) as DelegatooorFactory;
  }
  connect(signer: Signer): DelegatooorFactory__factory {
    return super.connect(signer) as DelegatooorFactory__factory;
  }
  static readonly contractName: "DelegatooorFactory";
  public readonly contractName: "DelegatooorFactory";
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DelegatooorFactoryInterface {
    return new utils.Interface(_abi) as DelegatooorFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DelegatooorFactory {
    return new Contract(address, _abi, signerOrProvider) as DelegatooorFactory;
  }
}
