/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import '@ethersproject/shims'
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers'
import { FunctionFragment, Result } from '@ethersproject/abi'
import { Listener, Provider } from '@ethersproject/providers'
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from './common'

export type ContractAgnosticSignatureStruct = {
  signature: BytesLike
  contractAddress: string
}

export type ContractAgnosticSignatureStructOutput = [string, string] & {
  signature: string
  contractAddress: string
}

export type CaveatStruct = { enforcer: string; terms: BytesLike }

export type CaveatStructOutput = [string, string] & {
  enforcer: string
  terms: string
}

export type DelegationStruct = {
  delegate: string
  authority: BytesLike
  caveats: CaveatStruct[]
  salt: BigNumberish
}

export type DelegationStructOutput = [
  string,
  string,
  CaveatStructOutput[],
  BigNumber,
] & {
  delegate: string
  authority: string
  caveats: CaveatStructOutput[]
  salt: BigNumber
}

export type SignedDelegationStruct = {
  message: DelegationStruct
  signature: BytesLike
  signer: string
}

export type SignedDelegationStructOutput = [
  DelegationStructOutput,
  string,
  string,
] & { message: DelegationStructOutput; signature: string; signer: string }

export type SignaturePayloadStruct = {
  delegations: SignedDelegationStruct[]
  signatures: ContractAgnosticSignatureStruct[]
}

export type SignaturePayloadStructOutput = [
  SignedDelegationStructOutput[],
  ContractAgnosticSignatureStructOutput[],
] & {
  delegations: SignedDelegationStructOutput[]
  signatures: ContractAgnosticSignatureStructOutput[]
}

export type ReplayProtectionStruct = {
  nonce: BigNumberish
  queue: BigNumberish
}

export type ReplayProtectionStructOutput = [BigNumber, BigNumber] & {
  nonce: BigNumber
  queue: BigNumber
}

export type TransactionStruct = {
  to: string
  gasLimit: BigNumberish
  value: BigNumberish
  data: BytesLike
}

export type TransactionStructOutput = [string, BigNumber, BigNumber, string] & {
  to: string
  gasLimit: BigNumber
  value: BigNumber
  data: string
}

export type InvocationStruct = {
  transaction: TransactionStruct
  authority: SignedDelegationStruct[]
}

export type InvocationStructOutput = [
  TransactionStructOutput,
  SignedDelegationStructOutput[],
] & {
  transaction: TransactionStructOutput
  authority: SignedDelegationStructOutput[]
}

export type BatchStruct = {
  invocations: InvocationStruct[]
  replayProtection: ReplayProtectionStruct
}

export type BatchStructOutput = [
  InvocationStructOutput[],
  ReplayProtectionStructOutput,
] & {
  invocations: InvocationStructOutput[]
  replayProtection: ReplayProtectionStructOutput
}

export type EIP712DomainStruct = {
  name: string
  version: string
  chainId: BigNumberish
  verifyingContract: string
}

export type EIP712DomainStructOutput = [string, string, BigNumber, string] & {
  name: string
  version: string
  chainId: BigNumber
  verifyingContract: string
}

export type MultisigParamsStruct = {
  signers: string[]
  threshold: BigNumberish
}

export type MultisigParamsStructOutput = [string[], BigNumber] & {
  signers: string[]
  threshold: BigNumber
}

export type SignedBatchStruct = {
  message: BatchStruct
  signature: BytesLike
  signer: string
}

export type SignedBatchStructOutput = [BatchStructOutput, string, string] & {
  message: BatchStructOutput
  signature: string
  signer: string
}

export type SignedMultisigParamsStruct = {
  message: MultisigParamsStruct
  signature: BytesLike
  signer: string
}

export type SignedMultisigParamsStructOutput = [
  MultisigParamsStructOutput,
  string,
  string,
] & { message: MultisigParamsStructOutput; signature: string; signer: string }

export type UserOperationStruct = {
  sender: string
  nonce: BigNumberish
  initCode: BytesLike
  callData: BytesLike
  callGasLimit: BigNumberish
  verificationGasLimit: BigNumberish
  preVerificationGas: BigNumberish
  maxFeePerGas: BigNumberish
  maxPriorityFeePerGas: BigNumberish
  paymasterAndData: BytesLike
  signature: BytesLike
}

export type UserOperationStructOutput = [
  string,
  BigNumber,
  string,
  string,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  string,
  string,
] & {
  sender: string
  nonce: BigNumber
  initCode: string
  callData: string
  callGasLimit: BigNumber
  verificationGasLimit: BigNumber
  preVerificationGas: BigNumber
  maxFeePerGas: BigNumber
  maxPriorityFeePerGas: BigNumber
  paymasterAndData: string
  signature: string
}

export interface Delegatable4337AccountInterface extends utils.Interface {
  contractName: 'Delegatable4337Account'
  functions: {
    'addDeposit()': FunctionFragment
    'decodeAgnosticSignatures(bytes)': FunctionFragment
    'decodeCallData(bytes)': FunctionFragment
    'decodeDelegationArray(bytes)': FunctionFragment
    'decodeSignature(bytes)': FunctionFragment
    'domainHash()': FunctionFragment
    'encodeDelegationArray((address,bytes32,(address,bytes)[],uint256)[])': FunctionFragment
    'entryPoint()': FunctionFragment
    'execute(address,uint256,bytes,(((address,bytes32,(address,bytes)[],uint256),bytes,address)[],(bytes,address)[]),(uint256,uint256))': FunctionFragment
    'getAddressArrayPacketHash(address[])': FunctionFragment
    'getBatchPacketHash((((address,uint256,uint256,bytes),((address,bytes32,(address,bytes)[],uint256),bytes,address)[])[],(uint256,uint256)))': FunctionFragment
    'getCaveatArrayPacketHash((address,bytes)[])': FunctionFragment
    'getCaveatPacketHash((address,bytes))': FunctionFragment
    'getDelegationPacketHash((address,bytes32,(address,bytes)[],uint256))': FunctionFragment
    'getDeposit()': FunctionFragment
    'getDomainHash()': FunctionFragment
    'getEIP712DomainHash(string,string,uint256,address)': FunctionFragment
    'getEip712DomainPacketHash((string,string,uint256,address))': FunctionFragment
    'getInvocationArrayPacketHash(((address,uint256,uint256,bytes),((address,bytes32,(address,bytes)[],uint256),bytes,address)[])[])': FunctionFragment
    'getInvocationPacketHash(((address,uint256,uint256,bytes),((address,bytes32,(address,bytes)[],uint256),bytes,address)[]))': FunctionFragment
    'getMultiNonce(address,uint256)': FunctionFragment
    'getMultisigparamsPacketHash((address[],uint256))': FunctionFragment
    'getNonce()': FunctionFragment
    'getOwners()': FunctionFragment
    'getReplayprotectionPacketHash((uint256,uint256))': FunctionFragment
    'getSignedbatchPacketHash(((((address,uint256,uint256,bytes),((address,bytes32,(address,bytes)[],uint256),bytes,address)[])[],(uint256,uint256)),bytes,address))': FunctionFragment
    'getSigneddelegationArrayPacketHash(((address,bytes32,(address,bytes)[],uint256),bytes,address)[])': FunctionFragment
    'getSigneddelegationPacketHash(((address,bytes32,(address,bytes)[],uint256),bytes,address))': FunctionFragment
    'getSignedmultisigparamsPacketHash(((address[],uint256),bytes,address))': FunctionFragment
    'getTransactionPacketHash((address,uint256,uint256,bytes))': FunctionFragment
    'isOwner(address)': FunctionFragment
    'isValidSignature(bytes32,bytes)': FunctionFragment
    'onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)': FunctionFragment
    'onERC1155Received(address,address,uint256,uint256,bytes)': FunctionFragment
    'onERC721Received(address,address,uint256,bytes)': FunctionFragment
    'owners(uint256)': FunctionFragment
    'supportsInterface(bytes4)': FunctionFragment
    'threshold()': FunctionFragment
    'tokensReceived(address,address,address,uint256,bytes,bytes)': FunctionFragment
    'updateSignerAddress(address,address)': FunctionFragment
    'updateSigners((address[],uint256))': FunctionFragment
    'validateUserOp((address,uint256,bytes,bytes,uint256,uint256,uint256,uint256,uint256,bytes,bytes),bytes32,uint256)': FunctionFragment
    'verifySignedBatch(((((address,uint256,uint256,bytes),((address,bytes32,(address,bytes)[],uint256),bytes,address)[])[],(uint256,uint256)),bytes,address))': FunctionFragment
    'verifySignedDelegation(((address,bytes32,(address,bytes)[],uint256),bytes,address))': FunctionFragment
    'verifySignedMultisigParams(((address[],uint256),bytes,address))': FunctionFragment
  }

  encodeFunctionData(functionFragment: 'addDeposit', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'decodeAgnosticSignatures',
    values: [BytesLike],
  ): string
  encodeFunctionData(
    functionFragment: 'decodeCallData',
    values: [BytesLike],
  ): string
  encodeFunctionData(
    functionFragment: 'decodeDelegationArray',
    values: [BytesLike],
  ): string
  encodeFunctionData(
    functionFragment: 'decodeSignature',
    values: [BytesLike],
  ): string
  encodeFunctionData(functionFragment: 'domainHash', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'encodeDelegationArray',
    values: [DelegationStruct[]],
  ): string
  encodeFunctionData(functionFragment: 'entryPoint', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'execute',
    values: [
      string,
      BigNumberish,
      BytesLike,
      SignaturePayloadStruct,
      ReplayProtectionStruct,
    ],
  ): string
  encodeFunctionData(
    functionFragment: 'getAddressArrayPacketHash',
    values: [string[]],
  ): string
  encodeFunctionData(
    functionFragment: 'getBatchPacketHash',
    values: [BatchStruct],
  ): string
  encodeFunctionData(
    functionFragment: 'getCaveatArrayPacketHash',
    values: [CaveatStruct[]],
  ): string
  encodeFunctionData(
    functionFragment: 'getCaveatPacketHash',
    values: [CaveatStruct],
  ): string
  encodeFunctionData(
    functionFragment: 'getDelegationPacketHash',
    values: [DelegationStruct],
  ): string
  encodeFunctionData(functionFragment: 'getDeposit', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'getDomainHash',
    values?: undefined,
  ): string
  encodeFunctionData(
    functionFragment: 'getEIP712DomainHash',
    values: [string, string, BigNumberish, string],
  ): string
  encodeFunctionData(
    functionFragment: 'getEip712DomainPacketHash',
    values: [EIP712DomainStruct],
  ): string
  encodeFunctionData(
    functionFragment: 'getInvocationArrayPacketHash',
    values: [InvocationStruct[]],
  ): string
  encodeFunctionData(
    functionFragment: 'getInvocationPacketHash',
    values: [InvocationStruct],
  ): string
  encodeFunctionData(
    functionFragment: 'getMultiNonce',
    values: [string, BigNumberish],
  ): string
  encodeFunctionData(
    functionFragment: 'getMultisigparamsPacketHash',
    values: [MultisigParamsStruct],
  ): string
  encodeFunctionData(functionFragment: 'getNonce', values?: undefined): string
  encodeFunctionData(functionFragment: 'getOwners', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'getReplayprotectionPacketHash',
    values: [ReplayProtectionStruct],
  ): string
  encodeFunctionData(
    functionFragment: 'getSignedbatchPacketHash',
    values: [SignedBatchStruct],
  ): string
  encodeFunctionData(
    functionFragment: 'getSigneddelegationArrayPacketHash',
    values: [SignedDelegationStruct[]],
  ): string
  encodeFunctionData(
    functionFragment: 'getSigneddelegationPacketHash',
    values: [SignedDelegationStruct],
  ): string
  encodeFunctionData(
    functionFragment: 'getSignedmultisigparamsPacketHash',
    values: [SignedMultisigParamsStruct],
  ): string
  encodeFunctionData(
    functionFragment: 'getTransactionPacketHash',
    values: [TransactionStruct],
  ): string
  encodeFunctionData(functionFragment: 'isOwner', values: [string]): string
  encodeFunctionData(
    functionFragment: 'isValidSignature',
    values: [BytesLike, BytesLike],
  ): string
  encodeFunctionData(
    functionFragment: 'onERC1155BatchReceived',
    values: [string, string, BigNumberish[], BigNumberish[], BytesLike],
  ): string
  encodeFunctionData(
    functionFragment: 'onERC1155Received',
    values: [string, string, BigNumberish, BigNumberish, BytesLike],
  ): string
  encodeFunctionData(
    functionFragment: 'onERC721Received',
    values: [string, string, BigNumberish, BytesLike],
  ): string
  encodeFunctionData(functionFragment: 'owners', values: [BigNumberish]): string
  encodeFunctionData(
    functionFragment: 'supportsInterface',
    values: [BytesLike],
  ): string
  encodeFunctionData(functionFragment: 'threshold', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'tokensReceived',
    values: [string, string, string, BigNumberish, BytesLike, BytesLike],
  ): string
  encodeFunctionData(
    functionFragment: 'updateSignerAddress',
    values: [string, string],
  ): string
  encodeFunctionData(
    functionFragment: 'updateSigners',
    values: [MultisigParamsStruct],
  ): string
  encodeFunctionData(
    functionFragment: 'validateUserOp',
    values: [UserOperationStruct, BytesLike, BigNumberish],
  ): string
  encodeFunctionData(
    functionFragment: 'verifySignedBatch',
    values: [SignedBatchStruct],
  ): string
  encodeFunctionData(
    functionFragment: 'verifySignedDelegation',
    values: [SignedDelegationStruct],
  ): string
  encodeFunctionData(
    functionFragment: 'verifySignedMultisigParams',
    values: [SignedMultisigParamsStruct],
  ): string

  decodeFunctionResult(functionFragment: 'addDeposit', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'decodeAgnosticSignatures',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'decodeCallData',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'decodeDelegationArray',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'decodeSignature',
    data: BytesLike,
  ): Result
  decodeFunctionResult(functionFragment: 'domainHash', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'encodeDelegationArray',
    data: BytesLike,
  ): Result
  decodeFunctionResult(functionFragment: 'entryPoint', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'execute', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'getAddressArrayPacketHash',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'getBatchPacketHash',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'getCaveatArrayPacketHash',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'getCaveatPacketHash',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'getDelegationPacketHash',
    data: BytesLike,
  ): Result
  decodeFunctionResult(functionFragment: 'getDeposit', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'getDomainHash',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'getEIP712DomainHash',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'getEip712DomainPacketHash',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'getInvocationArrayPacketHash',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'getInvocationPacketHash',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'getMultiNonce',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'getMultisigparamsPacketHash',
    data: BytesLike,
  ): Result
  decodeFunctionResult(functionFragment: 'getNonce', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'getOwners', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'getReplayprotectionPacketHash',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'getSignedbatchPacketHash',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'getSigneddelegationArrayPacketHash',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'getSigneddelegationPacketHash',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'getSignedmultisigparamsPacketHash',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'getTransactionPacketHash',
    data: BytesLike,
  ): Result
  decodeFunctionResult(functionFragment: 'isOwner', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'isValidSignature',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'onERC1155BatchReceived',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'onERC1155Received',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'onERC721Received',
    data: BytesLike,
  ): Result
  decodeFunctionResult(functionFragment: 'owners', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'supportsInterface',
    data: BytesLike,
  ): Result
  decodeFunctionResult(functionFragment: 'threshold', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'tokensReceived',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'updateSignerAddress',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'updateSigners',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'validateUserOp',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'verifySignedBatch',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'verifySignedDelegation',
    data: BytesLike,
  ): Result
  decodeFunctionResult(
    functionFragment: 'verifySignedMultisigParams',
    data: BytesLike,
  ): Result

  events: {}
}

export interface Delegatable4337Account extends BaseContract {
  contractName: 'Delegatable4337Account'
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  interface: Delegatable4337AccountInterface

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>
  listeners(eventName?: string): Array<Listener>
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this
  removeAllListeners(eventName?: string): this
  off: OnEvent<this>
  on: OnEvent<this>
  once: OnEvent<this>
  removeListener: OnEvent<this>

  functions: {
    addDeposit(
      overrides?: PayableOverrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    decodeAgnosticSignatures(
      signatureField: BytesLike,
      overrides?: CallOverrides,
    ): Promise<
      [ContractAgnosticSignatureStructOutput[]] & {
        payload: ContractAgnosticSignatureStructOutput[]
      }
    >

    decodeCallData(
      callData: BytesLike,
      overrides?: CallOverrides,
    ): Promise<
      [string, string, BigNumber, string] & {
        funcSig: string
        to: string
        value: BigNumber
        data: string
      }
    >

    decodeDelegationArray(
      encodedDelegationArray: BytesLike,
      overrides?: CallOverrides,
    ): Promise<
      [SignedDelegationStructOutput[]] & {
        delegationArray: SignedDelegationStructOutput[]
      }
    >

    decodeSignature(
      signatureField: BytesLike,
      overrides?: CallOverrides,
    ): Promise<
      [SignaturePayloadStructOutput] & { payload: SignaturePayloadStructOutput }
    >

    domainHash(overrides?: CallOverrides): Promise<[string]>

    encodeDelegationArray(
      delegationArray: DelegationStruct[],
      overrides?: CallOverrides,
    ): Promise<[string] & { encodedDelegationArray: string }>

    entryPoint(overrides?: CallOverrides): Promise<[string]>

    execute(
      _dest: string,
      _value: BigNumberish,
      _func: BytesLike,
      _signaturePayload: SignaturePayloadStruct,
      _protection: ReplayProtectionStruct,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    getAddressArrayPacketHash(
      _input: string[],
      overrides?: CallOverrides,
    ): Promise<[string]>

    getBatchPacketHash(
      _input: BatchStruct,
      overrides?: CallOverrides,
    ): Promise<[string]>

    getCaveatArrayPacketHash(
      _input: CaveatStruct[],
      overrides?: CallOverrides,
    ): Promise<[string]>

    getCaveatPacketHash(
      _input: CaveatStruct,
      overrides?: CallOverrides,
    ): Promise<[string]>

    getDelegationPacketHash(
      _input: DelegationStruct,
      overrides?: CallOverrides,
    ): Promise<[string]>

    getDeposit(overrides?: CallOverrides): Promise<[BigNumber]>

    getDomainHash(overrides?: CallOverrides): Promise<[string]>

    getEIP712DomainHash(
      contractName: string,
      version: string,
      chainId: BigNumberish,
      verifyingContract: string,
      overrides?: CallOverrides,
    ): Promise<[string]>

    getEip712DomainPacketHash(
      _input: EIP712DomainStruct,
      overrides?: CallOverrides,
    ): Promise<[string]>

    getInvocationArrayPacketHash(
      _input: InvocationStruct[],
      overrides?: CallOverrides,
    ): Promise<[string]>

    getInvocationPacketHash(
      _input: InvocationStruct,
      overrides?: CallOverrides,
    ): Promise<[string]>

    getMultiNonce(
      intendedSender: string,
      queue: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>

    getMultisigparamsPacketHash(
      _input: MultisigParamsStruct,
      overrides?: CallOverrides,
    ): Promise<[string]>

    getNonce(overrides?: CallOverrides): Promise<[BigNumber]>

    getOwners(overrides?: CallOverrides): Promise<[string[]]>

    getReplayprotectionPacketHash(
      _input: ReplayProtectionStruct,
      overrides?: CallOverrides,
    ): Promise<[string]>

    getSignedbatchPacketHash(
      _input: SignedBatchStruct,
      overrides?: CallOverrides,
    ): Promise<[string]>

    getSigneddelegationArrayPacketHash(
      _input: SignedDelegationStruct[],
      overrides?: CallOverrides,
    ): Promise<[string]>

    getSigneddelegationPacketHash(
      _input: SignedDelegationStruct,
      overrides?: CallOverrides,
    ): Promise<[string]>

    getSignedmultisigparamsPacketHash(
      _input: SignedMultisigParamsStruct,
      overrides?: CallOverrides,
    ): Promise<[string]>

    getTransactionPacketHash(
      _input: TransactionStruct,
      overrides?: CallOverrides,
    ): Promise<[string]>

    isOwner(arg0: string, overrides?: CallOverrides): Promise<[boolean]>

    isValidSignature(
      _hash: BytesLike,
      _signatures: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[string]>

    onERC1155BatchReceived(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[string]>

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[string]>

    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[string]>

    owners(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[boolean]>

    threshold(overrides?: CallOverrides): Promise<[number]>

    tokensReceived(
      arg0: string,
      arg1: string,
      arg2: string,
      arg3: BigNumberish,
      arg4: BytesLike,
      arg5: BytesLike,
      overrides?: CallOverrides,
    ): Promise<[void]>

    updateSignerAddress(
      _oldSigner: string,
      _newSigner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    updateSigners(
      params: MultisigParamsStruct,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    validateUserOp(
      userOp: UserOperationStruct,
      userOpHash: BytesLike,
      missingAccountFunds: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>

    verifySignedBatch(
      _input: SignedBatchStruct,
      overrides?: CallOverrides,
    ): Promise<[string]>

    verifySignedDelegation(
      _input: SignedDelegationStruct,
      overrides?: CallOverrides,
    ): Promise<[string]>

    verifySignedMultisigParams(
      _input: SignedMultisigParamsStruct,
      overrides?: CallOverrides,
    ): Promise<[string]>
  }

  addDeposit(
    overrides?: PayableOverrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  decodeAgnosticSignatures(
    signatureField: BytesLike,
    overrides?: CallOverrides,
  ): Promise<ContractAgnosticSignatureStructOutput[]>

  decodeCallData(
    callData: BytesLike,
    overrides?: CallOverrides,
  ): Promise<
    [string, string, BigNumber, string] & {
      funcSig: string
      to: string
      value: BigNumber
      data: string
    }
  >

  decodeDelegationArray(
    encodedDelegationArray: BytesLike,
    overrides?: CallOverrides,
  ): Promise<SignedDelegationStructOutput[]>

  decodeSignature(
    signatureField: BytesLike,
    overrides?: CallOverrides,
  ): Promise<SignaturePayloadStructOutput>

  domainHash(overrides?: CallOverrides): Promise<string>

  encodeDelegationArray(
    delegationArray: DelegationStruct[],
    overrides?: CallOverrides,
  ): Promise<string>

  entryPoint(overrides?: CallOverrides): Promise<string>

  execute(
    _dest: string,
    _value: BigNumberish,
    _func: BytesLike,
    _signaturePayload: SignaturePayloadStruct,
    _protection: ReplayProtectionStruct,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  getAddressArrayPacketHash(
    _input: string[],
    overrides?: CallOverrides,
  ): Promise<string>

  getBatchPacketHash(
    _input: BatchStruct,
    overrides?: CallOverrides,
  ): Promise<string>

  getCaveatArrayPacketHash(
    _input: CaveatStruct[],
    overrides?: CallOverrides,
  ): Promise<string>

  getCaveatPacketHash(
    _input: CaveatStruct,
    overrides?: CallOverrides,
  ): Promise<string>

  getDelegationPacketHash(
    _input: DelegationStruct,
    overrides?: CallOverrides,
  ): Promise<string>

  getDeposit(overrides?: CallOverrides): Promise<BigNumber>

  getDomainHash(overrides?: CallOverrides): Promise<string>

  getEIP712DomainHash(
    contractName: string,
    version: string,
    chainId: BigNumberish,
    verifyingContract: string,
    overrides?: CallOverrides,
  ): Promise<string>

  getEip712DomainPacketHash(
    _input: EIP712DomainStruct,
    overrides?: CallOverrides,
  ): Promise<string>

  getInvocationArrayPacketHash(
    _input: InvocationStruct[],
    overrides?: CallOverrides,
  ): Promise<string>

  getInvocationPacketHash(
    _input: InvocationStruct,
    overrides?: CallOverrides,
  ): Promise<string>

  getMultiNonce(
    intendedSender: string,
    queue: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<BigNumber>

  getMultisigparamsPacketHash(
    _input: MultisigParamsStruct,
    overrides?: CallOverrides,
  ): Promise<string>

  getNonce(overrides?: CallOverrides): Promise<BigNumber>

  getOwners(overrides?: CallOverrides): Promise<string[]>

  getReplayprotectionPacketHash(
    _input: ReplayProtectionStruct,
    overrides?: CallOverrides,
  ): Promise<string>

  getSignedbatchPacketHash(
    _input: SignedBatchStruct,
    overrides?: CallOverrides,
  ): Promise<string>

  getSigneddelegationArrayPacketHash(
    _input: SignedDelegationStruct[],
    overrides?: CallOverrides,
  ): Promise<string>

  getSigneddelegationPacketHash(
    _input: SignedDelegationStruct,
    overrides?: CallOverrides,
  ): Promise<string>

  getSignedmultisigparamsPacketHash(
    _input: SignedMultisigParamsStruct,
    overrides?: CallOverrides,
  ): Promise<string>

  getTransactionPacketHash(
    _input: TransactionStruct,
    overrides?: CallOverrides,
  ): Promise<string>

  isOwner(arg0: string, overrides?: CallOverrides): Promise<boolean>

  isValidSignature(
    _hash: BytesLike,
    _signatures: BytesLike,
    overrides?: CallOverrides,
  ): Promise<string>

  onERC1155BatchReceived(
    arg0: string,
    arg1: string,
    arg2: BigNumberish[],
    arg3: BigNumberish[],
    arg4: BytesLike,
    overrides?: CallOverrides,
  ): Promise<string>

  onERC1155Received(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    arg3: BigNumberish,
    arg4: BytesLike,
    overrides?: CallOverrides,
  ): Promise<string>

  onERC721Received(
    arg0: string,
    arg1: string,
    arg2: BigNumberish,
    arg3: BytesLike,
    overrides?: CallOverrides,
  ): Promise<string>

  owners(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides,
  ): Promise<boolean>

  threshold(overrides?: CallOverrides): Promise<number>

  tokensReceived(
    arg0: string,
    arg1: string,
    arg2: string,
    arg3: BigNumberish,
    arg4: BytesLike,
    arg5: BytesLike,
    overrides?: CallOverrides,
  ): Promise<void>

  updateSignerAddress(
    _oldSigner: string,
    _newSigner: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  updateSigners(
    params: MultisigParamsStruct,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  validateUserOp(
    userOp: UserOperationStruct,
    userOpHash: BytesLike,
    missingAccountFunds: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>

  verifySignedBatch(
    _input: SignedBatchStruct,
    overrides?: CallOverrides,
  ): Promise<string>

  verifySignedDelegation(
    _input: SignedDelegationStruct,
    overrides?: CallOverrides,
  ): Promise<string>

  verifySignedMultisigParams(
    _input: SignedMultisigParamsStruct,
    overrides?: CallOverrides,
  ): Promise<string>

  callStatic: {
    addDeposit(overrides?: CallOverrides): Promise<void>

    decodeAgnosticSignatures(
      signatureField: BytesLike,
      overrides?: CallOverrides,
    ): Promise<ContractAgnosticSignatureStructOutput[]>

    decodeCallData(
      callData: BytesLike,
      overrides?: CallOverrides,
    ): Promise<
      [string, string, BigNumber, string] & {
        funcSig: string
        to: string
        value: BigNumber
        data: string
      }
    >

    decodeDelegationArray(
      encodedDelegationArray: BytesLike,
      overrides?: CallOverrides,
    ): Promise<SignedDelegationStructOutput[]>

    decodeSignature(
      signatureField: BytesLike,
      overrides?: CallOverrides,
    ): Promise<SignaturePayloadStructOutput>

    domainHash(overrides?: CallOverrides): Promise<string>

    encodeDelegationArray(
      delegationArray: DelegationStruct[],
      overrides?: CallOverrides,
    ): Promise<string>

    entryPoint(overrides?: CallOverrides): Promise<string>

    execute(
      _dest: string,
      _value: BigNumberish,
      _func: BytesLike,
      _signaturePayload: SignaturePayloadStruct,
      _protection: ReplayProtectionStruct,
      overrides?: CallOverrides,
    ): Promise<void>

    getAddressArrayPacketHash(
      _input: string[],
      overrides?: CallOverrides,
    ): Promise<string>

    getBatchPacketHash(
      _input: BatchStruct,
      overrides?: CallOverrides,
    ): Promise<string>

    getCaveatArrayPacketHash(
      _input: CaveatStruct[],
      overrides?: CallOverrides,
    ): Promise<string>

    getCaveatPacketHash(
      _input: CaveatStruct,
      overrides?: CallOverrides,
    ): Promise<string>

    getDelegationPacketHash(
      _input: DelegationStruct,
      overrides?: CallOverrides,
    ): Promise<string>

    getDeposit(overrides?: CallOverrides): Promise<BigNumber>

    getDomainHash(overrides?: CallOverrides): Promise<string>

    getEIP712DomainHash(
      contractName: string,
      version: string,
      chainId: BigNumberish,
      verifyingContract: string,
      overrides?: CallOverrides,
    ): Promise<string>

    getEip712DomainPacketHash(
      _input: EIP712DomainStruct,
      overrides?: CallOverrides,
    ): Promise<string>

    getInvocationArrayPacketHash(
      _input: InvocationStruct[],
      overrides?: CallOverrides,
    ): Promise<string>

    getInvocationPacketHash(
      _input: InvocationStruct,
      overrides?: CallOverrides,
    ): Promise<string>

    getMultiNonce(
      intendedSender: string,
      queue: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    getMultisigparamsPacketHash(
      _input: MultisigParamsStruct,
      overrides?: CallOverrides,
    ): Promise<string>

    getNonce(overrides?: CallOverrides): Promise<BigNumber>

    getOwners(overrides?: CallOverrides): Promise<string[]>

    getReplayprotectionPacketHash(
      _input: ReplayProtectionStruct,
      overrides?: CallOverrides,
    ): Promise<string>

    getSignedbatchPacketHash(
      _input: SignedBatchStruct,
      overrides?: CallOverrides,
    ): Promise<string>

    getSigneddelegationArrayPacketHash(
      _input: SignedDelegationStruct[],
      overrides?: CallOverrides,
    ): Promise<string>

    getSigneddelegationPacketHash(
      _input: SignedDelegationStruct,
      overrides?: CallOverrides,
    ): Promise<string>

    getSignedmultisigparamsPacketHash(
      _input: SignedMultisigParamsStruct,
      overrides?: CallOverrides,
    ): Promise<string>

    getTransactionPacketHash(
      _input: TransactionStruct,
      overrides?: CallOverrides,
    ): Promise<string>

    isOwner(arg0: string, overrides?: CallOverrides): Promise<boolean>

    isValidSignature(
      _hash: BytesLike,
      _signatures: BytesLike,
      overrides?: CallOverrides,
    ): Promise<string>

    onERC1155BatchReceived(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: CallOverrides,
    ): Promise<string>

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: CallOverrides,
    ): Promise<string>

    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: CallOverrides,
    ): Promise<string>

    owners(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides,
    ): Promise<boolean>

    threshold(overrides?: CallOverrides): Promise<number>

    tokensReceived(
      arg0: string,
      arg1: string,
      arg2: string,
      arg3: BigNumberish,
      arg4: BytesLike,
      arg5: BytesLike,
      overrides?: CallOverrides,
    ): Promise<void>

    updateSignerAddress(
      _oldSigner: string,
      _newSigner: string,
      overrides?: CallOverrides,
    ): Promise<void>

    updateSigners(
      params: MultisigParamsStruct,
      overrides?: CallOverrides,
    ): Promise<void>

    validateUserOp(
      userOp: UserOperationStruct,
      userOpHash: BytesLike,
      missingAccountFunds: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    verifySignedBatch(
      _input: SignedBatchStruct,
      overrides?: CallOverrides,
    ): Promise<string>

    verifySignedDelegation(
      _input: SignedDelegationStruct,
      overrides?: CallOverrides,
    ): Promise<string>

    verifySignedMultisigParams(
      _input: SignedMultisigParamsStruct,
      overrides?: CallOverrides,
    ): Promise<string>
  }

  filters: {}

  estimateGas: {
    addDeposit(
      overrides?: PayableOverrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    decodeAgnosticSignatures(
      signatureField: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    decodeCallData(
      callData: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    decodeDelegationArray(
      encodedDelegationArray: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    decodeSignature(
      signatureField: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    domainHash(overrides?: CallOverrides): Promise<BigNumber>

    encodeDelegationArray(
      delegationArray: DelegationStruct[],
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    entryPoint(overrides?: CallOverrides): Promise<BigNumber>

    execute(
      _dest: string,
      _value: BigNumberish,
      _func: BytesLike,
      _signaturePayload: SignaturePayloadStruct,
      _protection: ReplayProtectionStruct,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    getAddressArrayPacketHash(
      _input: string[],
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    getBatchPacketHash(
      _input: BatchStruct,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    getCaveatArrayPacketHash(
      _input: CaveatStruct[],
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    getCaveatPacketHash(
      _input: CaveatStruct,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    getDelegationPacketHash(
      _input: DelegationStruct,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    getDeposit(overrides?: CallOverrides): Promise<BigNumber>

    getDomainHash(overrides?: CallOverrides): Promise<BigNumber>

    getEIP712DomainHash(
      contractName: string,
      version: string,
      chainId: BigNumberish,
      verifyingContract: string,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    getEip712DomainPacketHash(
      _input: EIP712DomainStruct,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    getInvocationArrayPacketHash(
      _input: InvocationStruct[],
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    getInvocationPacketHash(
      _input: InvocationStruct,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    getMultiNonce(
      intendedSender: string,
      queue: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    getMultisigparamsPacketHash(
      _input: MultisigParamsStruct,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    getNonce(overrides?: CallOverrides): Promise<BigNumber>

    getOwners(overrides?: CallOverrides): Promise<BigNumber>

    getReplayprotectionPacketHash(
      _input: ReplayProtectionStruct,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    getSignedbatchPacketHash(
      _input: SignedBatchStruct,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    getSigneddelegationArrayPacketHash(
      _input: SignedDelegationStruct[],
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    getSigneddelegationPacketHash(
      _input: SignedDelegationStruct,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    getSignedmultisigparamsPacketHash(
      _input: SignedMultisigParamsStruct,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    getTransactionPacketHash(
      _input: TransactionStruct,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    isOwner(arg0: string, overrides?: CallOverrides): Promise<BigNumber>

    isValidSignature(
      _hash: BytesLike,
      _signatures: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    onERC1155BatchReceived(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    owners(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    threshold(overrides?: CallOverrides): Promise<BigNumber>

    tokensReceived(
      arg0: string,
      arg1: string,
      arg2: string,
      arg3: BigNumberish,
      arg4: BytesLike,
      arg5: BytesLike,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    updateSignerAddress(
      _oldSigner: string,
      _newSigner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    updateSigners(
      params: MultisigParamsStruct,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    validateUserOp(
      userOp: UserOperationStruct,
      userOpHash: BytesLike,
      missingAccountFunds: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>

    verifySignedBatch(
      _input: SignedBatchStruct,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    verifySignedDelegation(
      _input: SignedDelegationStruct,
      overrides?: CallOverrides,
    ): Promise<BigNumber>

    verifySignedMultisigParams(
      _input: SignedMultisigParamsStruct,
      overrides?: CallOverrides,
    ): Promise<BigNumber>
  }

  populateTransaction: {
    addDeposit(
      overrides?: PayableOverrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    decodeAgnosticSignatures(
      signatureField: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    decodeCallData(
      callData: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    decodeDelegationArray(
      encodedDelegationArray: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    decodeSignature(
      signatureField: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    domainHash(overrides?: CallOverrides): Promise<PopulatedTransaction>

    encodeDelegationArray(
      delegationArray: DelegationStruct[],
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    entryPoint(overrides?: CallOverrides): Promise<PopulatedTransaction>

    execute(
      _dest: string,
      _value: BigNumberish,
      _func: BytesLike,
      _signaturePayload: SignaturePayloadStruct,
      _protection: ReplayProtectionStruct,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    getAddressArrayPacketHash(
      _input: string[],
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    getBatchPacketHash(
      _input: BatchStruct,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    getCaveatArrayPacketHash(
      _input: CaveatStruct[],
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    getCaveatPacketHash(
      _input: CaveatStruct,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    getDelegationPacketHash(
      _input: DelegationStruct,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    getDeposit(overrides?: CallOverrides): Promise<PopulatedTransaction>

    getDomainHash(overrides?: CallOverrides): Promise<PopulatedTransaction>

    getEIP712DomainHash(
      contractName: string,
      version: string,
      chainId: BigNumberish,
      verifyingContract: string,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    getEip712DomainPacketHash(
      _input: EIP712DomainStruct,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    getInvocationArrayPacketHash(
      _input: InvocationStruct[],
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    getInvocationPacketHash(
      _input: InvocationStruct,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    getMultiNonce(
      intendedSender: string,
      queue: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    getMultisigparamsPacketHash(
      _input: MultisigParamsStruct,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    getNonce(overrides?: CallOverrides): Promise<PopulatedTransaction>

    getOwners(overrides?: CallOverrides): Promise<PopulatedTransaction>

    getReplayprotectionPacketHash(
      _input: ReplayProtectionStruct,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    getSignedbatchPacketHash(
      _input: SignedBatchStruct,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    getSigneddelegationArrayPacketHash(
      _input: SignedDelegationStruct[],
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    getSigneddelegationPacketHash(
      _input: SignedDelegationStruct,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    getSignedmultisigparamsPacketHash(
      _input: SignedMultisigParamsStruct,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    getTransactionPacketHash(
      _input: TransactionStruct,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    isOwner(
      arg0: string,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    isValidSignature(
      _hash: BytesLike,
      _signatures: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    onERC1155BatchReceived(
      arg0: string,
      arg1: string,
      arg2: BigNumberish[],
      arg3: BigNumberish[],
      arg4: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    onERC1155Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    onERC721Received(
      arg0: string,
      arg1: string,
      arg2: BigNumberish,
      arg3: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    owners(
      arg0: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    threshold(overrides?: CallOverrides): Promise<PopulatedTransaction>

    tokensReceived(
      arg0: string,
      arg1: string,
      arg2: string,
      arg3: BigNumberish,
      arg4: BytesLike,
      arg5: BytesLike,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    updateSignerAddress(
      _oldSigner: string,
      _newSigner: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    updateSigners(
      params: MultisigParamsStruct,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    validateUserOp(
      userOp: UserOperationStruct,
      userOpHash: BytesLike,
      missingAccountFunds: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>

    verifySignedBatch(
      _input: SignedBatchStruct,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    verifySignedDelegation(
      _input: SignedDelegationStruct,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>

    verifySignedMultisigParams(
      _input: SignedMultisigParamsStruct,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>
  }
}
