/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface DelegatooorFactoryInterface extends utils.Interface {
  contractName: "DelegatooorFactory";
  functions: {
    "deploy(bytes,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "deploy",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "deploy", data: BytesLike): Result;

  events: {
    "DelegatooorDeploy(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DelegatooorDeploy"): EventFragment;
}

export type DelegatooorDeployEvent = TypedEvent<[string], { addr: string }>;

export type DelegatooorDeployEventFilter =
  TypedEventFilter<DelegatooorDeployEvent>;

export interface DelegatooorFactory extends BaseContract {
  contractName: "DelegatooorFactory";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: DelegatooorFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    deploy(
      _bytecode: BytesLike,
      _salt: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  deploy(
    _bytecode: BytesLike,
    _salt: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    deploy(
      _bytecode: BytesLike,
      _salt: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "DelegatooorDeploy(address)"(addr?: null): DelegatooorDeployEventFilter;
    DelegatooorDeploy(addr?: null): DelegatooorDeployEventFilter;
  };

  estimateGas: {
    deploy(
      _bytecode: BytesLike,
      _salt: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    deploy(
      _bytecode: BytesLike,
      _salt: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
